In [1]:
import pandas as pd
import numpy as np
products= pd.read_csv('fashion.csv')

products

,ProductId,Gender,Category,SubCategory,ProductType,Colour,Usage,ProductTitle,Image,ImageURL
0,42419,Girls,Apparel,Topwear,Tops,White,Casual,Gini and Jony Girls Knit White Top,42419.jpg,http://assets.myntassets.com/v1/images/style/p...
1,34009,Girls,Apparel,Topwear,Tops,Black,Casual,Gini and Jony Girls Black Top,34009.jpg,http://assets.myntassets.com/v1/images/style/p...
2,40143,Girls,Apparel,Topwear,Tops,Blue,Casual,Gini and Jony Girls Pretty Blossom Blue Top,40143.jpg,http://assets.myntassets.com/v1/images/style/p...
3,23623,Girls,Apparel,Topwear,Tops,Pink,Casual,Doodle Kids Girls Pink I love Shopping Top,23623.jpg,http://assets.myntassets.com/v1/images/style/p...
4,47154,Girls,Apparel,Bottomwear,Capris,Black,Casual,Gini and Jony Girls Black Capris,47154.jpg,http://assets.myntassets.com/v1/images/style/p...
...,...,...,...,...,...,...,...,...,...,...
2901,51755,Women,Footwear,Shoes,Casual Shoes,Black,Casual,Catwalk Women Black Shoes,51755.jpg,http://assets.myntassets.com/v1/images/style/p...
2902,47630,Women,Footwear,Shoes,Flats,Blue,Casual,Carlton London Women Blue Shoes,47630.jpg,http://assets.myntassets.com/v1/images/style/p...
2903,32836,Women,Footwear,Shoes,Flats,Pink,Casual,Grendha Women Flori Pink Sandals,32836.jpg,http://assets.myntassets.com/v1/images/style/p...
2904,35821,Women,Footwear,Shoes,Heels,Black,Casual,Enroute Women Black Heels,35821.jpg,http://assets.myntassets.com/v1/images/style/p...
2905,18553,Women,Footwear,Shoes,Heels,Blue,Casual,Catwalk Women Mary Janes Blue Flats,18553.jpg,http://assets.myntassets.com/v1/images/style/p...

In [4]:
products['name'] = products['Gender']  + ' ' + products['Category'] +  ' ' + products['Usage']+' ' + products['SubCategory'] + ' ' + products['Colour'] + ' ' + products['ProductTitle']

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

cv= CountVectorizer(max_features=2000, stop_words='english' )

In [6]:
vectors=cv.fit_transform(products['name']).toarray()

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
similarity=cosine_similarity(vectors)

In [9]:
def recommend(product_name):
    matches = products[products['name'].str.contains(product_name, case=False)]
    data = []

    if not matches.empty:
        searched_index = matches.index[0]  # Get the index of the first match
        similar_items_all = []
        for index in matches.index:
            similar_items = sorted(list(enumerate(similarity[index])), key=lambda x: x[1], reverse=True)[1:6]
            similar_items_all.extend(similar_items)
        similar_items_all = sorted(similar_items_all, key=lambda x: x[1], reverse=True)

        recommended_indices = set()  # To keep track of recommended product indices
        recommended_count = 0

        for product_index, score in similar_items_all:
            if product_index != searched_index and product_index not in recommended_indices:
                # Add the product index to the set of recommended indices
                recommended_indices.add(product_index)
                recommended_count += 1
                if recommended_count > 5:
                    break  # Stop when 5 unique recommendations are found
                item = []
                temp_df = products.iloc[product_index]
                item.append(temp_df['ProductTitle'])

                item.append(temp_df['ImageURL'])
                data.append(item)
    else:
        print("No products found matching the specified partial name.")

    return data

In [11]:
recommend('shoes')

[['Arrow Men Black Formal Shoes',
  'http://assets.myntassets.com/v1/images/style/properties/8f3b9f4c5f554e39681567b22985966e_images.jpg'],
 ['Arrow Men Formal Black Shoes',
  'http://assets.myntassets.com/v1/images/style/properties/ae9b19f9e5b20995dd206e0400b2dbce_images.jpg'],
 ['Arrow Men Black Formal Shoes',
  'http://assets.myntassets.com/v1/images/style/properties/a05fe01290b257157bc99ca67515ad3e_images.jpg'],
 ['Timberland Men Black Casual Shoes',
  'http://assets.myntassets.com/v1/images/style/properties/5863961b3510970c2e31d466af69b32b_images.jpg'],
 ['Timberland Men Black Casual Shoes',
  'http://assets.myntassets.com/v1/images/style/properties/13b63be853066689953a150fe1986bba_images.jpg']]

In [13]:
import pickle
# pickle.dump(vectors,open('pt.pkl','wb'))
pickle.dump(products,open('products.pkl','wb'))
pickle.dump(similarity,open('similarity_score.pkl','wb'))

In [14]:
products

,ProductId,Gender,Category,SubCategory,ProductType,Colour,Usage,ProductTitle,Image,ImageURL,name
0,42419,Girls,Apparel,Topwear,Tops,White,Casual,Gini and Jony Girls Knit White Top,42419.jpg,http://assets.myntassets.com/v1/images/style/p...,Girls Apparel Casual Topwear White Gini and Jo...
1,34009,Girls,Apparel,Topwear,Tops,Black,Casual,Gini and Jony Girls Black Top,34009.jpg,http://assets.myntassets.com/v1/images/style/p...,Girls Apparel Casual Topwear Black Gini and Jo...
2,40143,Girls,Apparel,Topwear,Tops,Blue,Casual,Gini and Jony Girls Pretty Blossom Blue Top,40143.jpg,http://assets.myntassets.com/v1/images/style/p...,Girls Apparel Casual Topwear Blue Gini and Jon...
3,23623,Girls,Apparel,Topwear,Tops,Pink,Casual,Doodle Kids Girls Pink I love Shopping Top,23623.jpg,http://assets.myntassets.com/v1/images/style/p...,Girls Apparel Casual Topwear Pink Doodle Kids ...
4,47154,Girls,Apparel,Bottomwear,Capris,Black,Casual,Gini and Jony Girls Black Capris,47154.jpg,http://assets.myntassets.com/v1/images/style/p...,Girls Apparel Casual Bottomwear Black Gini and...
...,...,...,...,...,...,...,...,...,...,...,...
2901,51755,Women,Footwear,Shoes,Casual Shoes,Black,Casual,Catwalk Women Black Shoes,51755.jpg,http://assets.myntassets.com/v1/images/style/p...,Women Footwear Casual Shoes Black Catwalk Wome...
2902,47630,Women,Footwear,Shoes,Flats,Blue,Casual,Carlton London Women Blue Shoes,47630.jpg,http://assets.myntassets.com/v1/images/style/p...,Women Footwear Casual Shoes Blue Carlton Londo...
2903,32836,Women,Footwear,Shoes,Flats,Pink,Casual,Grendha Women Flori Pink Sandals,32836.jpg,http://assets.myntassets.com/v1/images/style/p...,Women Footwear Casual Shoes Pink Grendha Women...
2904,35821,Women,Footwear,Shoes,Heels,Black,Casual,Enroute Women Black Heels,35821.jpg,http://assets.myntassets.com/v1/images/style/p...,Women Footwear Casual Shoes Black Enroute Wome...
2905,18553,Women,Footwear,Shoes,Heels,Blue,Casual,Catwalk Women Mary Janes Blue Flats,18553.jpg,http://assets.myntassets.com/v1/images/style/p...,Women Footwear Casual Shoes Blue Catwalk Women...

In [15]:
products['ImageNumber'] = products['Image'].str.replace('.jpg', '').astype(int)

In [18]:
sorted_product = products.sort_values(by='ImageNumber')

In [19]:
sorted_product

,ProductId,Gender,Category,SubCategory,ProductType,Colour,Usage,ProductTitle,Image,ImageURL,name,ImageNumber
1503,1636,Men,Footwear,Shoes,Sports Shoes,White,Sports,Nike Men Air Zoom Century Shoes,1636.jpg,http://assets.myntassets.com/v1/images/style/p...,Men Footwear Sports Shoes White Nike Men Air Z...,1636
1743,1637,Men,Footwear,Shoes,Sports Shoes,White,Sports,Nike Men White Cricket Shoes,1637.jpg,http://assets.myntassets.com/v1/images/style/p...,Men Footwear Sports Shoes White Nike Men White...,1637
1635,1653,Men,Footwear,Shoes,Sports Shoes,Brown,Sports,Reebok Men's Ventilator Ubiq Shoe,1653.jpg,http://assets.myntassets.com/v1/images/style/p...,Men Footwear Sports Shoes Brown Reebok Men's V...,1653
1659,1654,Men,Footwear,Shoes,Sports Shoes,White,Sports,Reebok Men's Frisker LP Shoe,1654.jpg,http://assets.myntassets.com/v1/images/style/p...,Men Footwear Sports Shoes White Reebok Men's F...,1654
1655,1806,Men,Footwear,Sandal,Sandals,Brown,Casual,Quechua Men Arpenaz Brown Sandal,1806.jpg,http://assets.myntassets.com/v1/images/style/p...,Men Footwear Casual Sandal Brown Quechua Men A...,1806
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,59435,Men,Footwear,Shoes,Formal Shoes,Black,Formal,Arrow Men Black Formal Shoes,59435.jpg,http://assets.myntassets.com/v1/images/style/p...,Men Footwear Formal Shoes Black Arrow Men Blac...,59435
2825,59757,Women,Footwear,Shoes,Heels,Black,Casual,Rocia Women Black Flats,59757.jpg,http://assets.myntassets.com/v1/images/style/p...,Women Footwear Casual Shoes Black Rocia Women ...,59757
2867,59759,Women,Footwear,Shoes,Heels,Black,Casual,Rocia Women Black Flats,59759.jpg,http://assets.myntassets.com/v1/images/style/p...,Women Footwear Casual Shoes Black Rocia Women ...,59759
2881,59761,Women,Footwear,Shoes,Flats,Black,Casual,Rocia Women Black Flats,59761.jpg,http://assets.myntassets.com/v1/images/style/p...,Women Footwear Casual Shoes Black Rocia Women ...,59761
2105,59943,Men,Footwear,Shoes,Casual Shoes,Black,Casual,Vans Men Black & Red Casual Shoes,59943.jpg,http://assets.myntassets.com/v1/images/style/p...,Men Footwear Casual Shoes Black Vans Men Black...,59943

In [20]:
pickle.dump(sorted_product,open('sorted_product.pkl','wb'))